# This is a basic workflow to help you get started with Actions

name: Test3

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"

  mailer:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      SMTP_SERVER: mail.sonic.net
      SMTP_PORT: 465
      MAIL_SUBJECT: "GitHub mail"
      MAIL_BODY: "Send an email"
      FROM: "shorner@sonic.net"
      TO: "zephod4321@gmail.com"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Send email via SMTP
        
        uses: dawidd6/action-send-mail@v10
        with:
          # SMTP Server
          server_address: ${{ env.SMTP_SERVER }}
          server_port: ${{ env.SMTP_PORT }}
          secure: true   # true if your server requires TLS on connect; with STARTTLS use false

          # Credentials
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}

          # Message
          subject: ${{ env.MAIL_SUBJECT }}
          to: ${{ env.TO }}
          body: ${{ env.MAIL_BODY }}    
          from: ${{ env.FROM }}

       # Runs a single command using the runners shell
       # -name: Run a one-line script
       # run: echo did it work

       # Runs a set of commands using the runners shell
       # -name: Run a multi-line script
       # run: |
      #   echo Add other actions if you can to build,
      #   echo test, and deploy your project.
